In [2]:
import numpy as np
from scipy import linalg
import time


In [3]:
P0=np.load("./data/p0.npy")
P1=np.load("./data/p1.npy")

In [4]:
P1

array([[320.        , 788.82683613],
       [311.60746914, 788.83225613],
       [303.18294956, 788.84096208],
       ...,
       [460.85363851,  38.69969541],
       [472.33393162,  38.71294764],
       [484.06239566,  38.71496746]])

In [5]:

from scipy.interpolate import Rbf

In [6]:
x=P1[:,1]
y=P1[:,0]
z=P0[:,0]
t1=time.time()
rbf0=Rbf(x,y,z,function="thin_plate", smooth=0.1)
t2=time.time()
A=rbf0.A
di=rbf0.di
w=rbf0.nodes
t2-t1

0.09676909446716309

In [7]:
rbf0(x[0],y[0]),z[0]

(array(987.99999771), 988.0)

In [8]:
from scipy.special import xlogy
from scipy.spatial.distance import cdist, pdist, squareform


In [19]:
xi=np.vstack([x,y])
di=z
N=x.shape[0]
xi_pdist=pdist(xi.T,"euclidean")
r_dist = squareform(xi_pdist) 
r=r_dist
init_f = xlogy(r**2, r)
init_f.shape
myA=init_f-np.eye(N)*0.1
myw=linalg.solve(myA, di)
r.sum(),init_f.sum(),"   ",A.sum(),myA.sum(),w.sum(),myw.sum()
# Pairwise norm
        # return self._init_function(r) - np.eye(self.N)*self.smooth

(265532804.60104138,
 617317577646.1301,
 '   ',
 617317577552.3302,
 617317577552.3302,
 -0.00014090773926164757,
 -0.00014090773926164757)

In [10]:
np.savetxt("./data/py-input-x",x,fmt="%.8f")
np.savetxt("./data/py-input-y",y,fmt="%.8f")
np.savetxt("./data/py-input-z",z,fmt="%.8f")
np.savetxt("./data/py-get-dist",r,fmt="%.8f")
np.savetxt("./data/py-get-f",init_f,fmt="%.8f")
np.savetxt("./data/py-get-A",myA,fmt="%.8f")
np.savetxt("./data/py-get-w",myw,fmt="%.8f")

In [11]:
r.shape

(938, 938)

In [12]:
init_f.shape

(938, 938)

In [13]:
init_f

array([[0.00000000e+00, 1.49838514e+02, 7.98210697e+02, ...,
        3.86658587e+06, 3.89047295e+06, 3.91695419e+06],
       [1.49838514e+02, 0.00000000e+00, 1.51253055e+02, ...,
        3.88402410e+06, 3.90929452e+06, 3.93719082e+06],
       [7.98210697e+02, 1.51253055e+02, 0.00000000e+00, ...,
        3.90258073e+06, 3.92924103e+06, 3.95855916e+06],
       ...,
       [3.86658587e+06, 3.88402410e+06, 3.90258073e+06, ...,
        0.00000000e+00, 3.21668799e+02, 1.69379046e+03],
       [3.89047295e+06, 3.90929452e+06, 3.92924103e+06, ...,
        3.21668799e+02, 0.00000000e+00, 3.38667597e+02],
       [3.91695419e+06, 3.93719082e+06, 3.95855916e+06, ...,
        1.69379046e+03, 3.38667597e+02, 0.00000000e+00]])

In [14]:
np.eye(N)*0.1

array([[0.1, 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0.1, 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0.1, ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0.1, 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0.1, 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0.1]])

In [15]:
np.argwhere(r>0)

array([[  0,   1],
       [  0,   2],
       [  0,   3],
       ...,
       [937, 934],
       [937, 935],
       [937, 936]])

In [16]:
init_f.sum()-617317577646.5830,A.sum()-617317577552.7841

(-0.452880859375, -0.453857421875)

In [17]:
np.eye(N)*0.1

array([[0.1, 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0.1, 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0.1, ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0.1, 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0.1, 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0.1]])

In [18]:
x[0],y[0],z[0]

(788.826836126515, 320.0, 988.0)