In [9]:
import numpy as np
from scipy import linalg
import time


In [10]:
P0=np.load("./data/p0.npy")
P1=np.load("./data/p1.npy")

In [11]:
P1.shape

(938, 2)

In [12]:

from scipy.interpolate import Rbf

In [13]:
x=P1[:,1]
y=P1[:,0]
z=P0[:,0]
t1=time.time()
rbf0=Rbf(x,y,z,function="thin_plate", smooth=0.1)
t2=time.time()
A=rbf0.A
di=rbf0.di
w=rbf0.nodes
t2-t1



0.05944085121154785

In [21]:
xy=np.vstack((x,y))
xy.shape
myr = [1,10,100,200,300,400,500]
for i in myr:
    slide = xy[:,:i]
    print(slide.shape)
    t1 = time.time()
    rbf0(slide[0],slide[1])
    t2 = time.time()
    print(t2-t1)


(2, 1)
0.0005848407745361328
(2, 10)
0.0005908012390136719
(2, 100)
0.0036630630493164062
(2, 200)
0.007415056228637695
(2, 300)
0.008799314498901367
(2, 400)
0.010078907012939453
(2, 500)
0.015596866607666016


In [8]:
x.shape,y.shape,z.shape

((938,), (938,), (938,))

In [6]:
rbf0(x[0],y[0]),z[0]

(array(987.99999771), 988.0)

In [7]:
from scipy.special import xlogy
from scipy.spatial.distance import cdist, pdist, squareform


In [8]:
xi=np.vstack([x,y])
di=z
N=x.shape[0]
xi_pdist=pdist(xi.T,"euclidean")
r_dist = squareform(xi_pdist) 
r=r_dist
init_f = xlogy(r**2, r)
init_f.shape
myA=init_f-np.eye(N)*0.1
myw=linalg.solve(myA, di)
r.sum(),init_f.sum(),"   ",A.sum(),myA.sum(),w.sum(),myw.sum()
# Pairwise norm
        # return self._init_function(r) - np.eye(self.N)*self.smooth

(265532804.60104138,
 617317577646.1301,
 '   ',
 617317577552.3302,
 617317577552.3302,
 -0.00014090773926164757,
 -0.00014090773926164757)

In [9]:
np.savetxt("./data/py-input-x",x,fmt="%.8f")
np.savetxt("./data/py-input-y",y,fmt="%.8f")
np.savetxt("./data/py-input-z",z,fmt="%.8f")
np.savetxt("./data/py-get-dist",r,fmt="%.8f")
np.savetxt("./data/py-get-f",init_f,fmt="%.8f")
np.savetxt("./data/py-get-A",myA,fmt="%.8f")
np.savetxt("./data/py-get-w",myw,fmt="%.8f")

In [10]:
r.shape

(938, 938)

In [11]:
init_f.shape

(938, 938)

In [12]:
init_f

array([[0.00000000e+00, 1.49838514e+02, 7.98210697e+02, ...,
        3.86658587e+06, 3.89047295e+06, 3.91695419e+06],
       [1.49838514e+02, 0.00000000e+00, 1.51253055e+02, ...,
        3.88402410e+06, 3.90929452e+06, 3.93719082e+06],
       [7.98210697e+02, 1.51253055e+02, 0.00000000e+00, ...,
        3.90258073e+06, 3.92924103e+06, 3.95855916e+06],
       ...,
       [3.86658587e+06, 3.88402410e+06, 3.90258073e+06, ...,
        0.00000000e+00, 3.21668799e+02, 1.69379046e+03],
       [3.89047295e+06, 3.90929452e+06, 3.92924103e+06, ...,
        3.21668799e+02, 0.00000000e+00, 3.38667597e+02],
       [3.91695419e+06, 3.93719082e+06, 3.95855916e+06, ...,
        1.69379046e+03, 3.38667597e+02, 0.00000000e+00]])

In [13]:
np.eye(N)*0.1

array([[0.1, 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0.1, 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0.1, ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0.1, 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0.1, 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0.1]])

In [14]:
np.argwhere(r>0)

array([[  0,   1],
       [  0,   2],
       [  0,   3],
       ...,
       [937, 934],
       [937, 935],
       [937, 936]])

In [15]:
init_f.sum()-617317577646.5830,A.sum()-617317577552.7841

(-0.452880859375, -0.453857421875)

In [16]:
np.eye(N)*0.1

array([[0.1, 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0.1, 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0.1, ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0.1, 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0.1, 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0.1]])

In [17]:
x[0],y[0],z[0]

(788.826836126515, 320.0, 988.0)

In [18]:
0*np.log(r)[0,0]

nan

In [19]:
r[0][0]*np.log(r)[0][0]

nan

In [22]:
y

array([320.        , 311.60746914, 303.18294956, 294.71761603,
       286.20477932, 277.63190916, 268.98769339, 260.25529123,
       251.41544075, 242.442137  , 233.30164259, 223.94832891,
       214.32055243, 204.33536526, 193.88104098, 182.80635953,
       170.94241334, 158.02994777, 144.22411257, 320.        ,
       328.36680611, 336.71420494, 345.04679445, 353.3696125 ,
       361.68620821, 369.99993929, 378.31355188, 386.62902855,
       394.94917667, 403.27660033, 411.61566164, 419.97081651,
       428.34840239, 436.75456995, 445.1978842 , 453.6863036 ,
       462.23112384, 470.84187077, 479.53337927, 488.31578778,
       497.20885508, 506.22146703, 515.37937963, 524.69645749,
       534.20431939, 543.938207  , 553.95756014, 564.33485541,
       575.14296254, 586.45784713, 598.32872025, 320.        ,
       311.77655712, 303.51080201, 295.18756037, 286.78683472,
       278.28410612, 269.65074876, 260.85185605, 251.84809606,
       242.5926819 , 233.03370482, 223.11255724, 212.76